name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://yah236rr39-netizen:$HF_TOKEN@huggingface.co/spaces/Newt10806/10806SeverTranslatorBot main
